### ISSUE TITLE
Cannot create NRQL service, choosing NRQL from the provider list crashes the application

### ISSUE THREAD

**Issue by jsbnr** [newrelic/nr1-status-pages#113]
As soon as you select "NRQL" from the provider list crashes the application. Console errors show "Cannot read property 'inputValue' of undefined"

## Steps to Reproduce

- Click "Add New Service"
- Select NRQL from Provider dropdown
- Observe crash

## Expected Behaviour

Expect to be able to specify NRQL query

## Relevant Logs / Console output

```
ncaught TypeError: Cannot read property 'inputValue' of undefined
    at c.value (VM17 dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1)
    at finishClassComponent (VM9 react-dom.development.js:14425)
    at updateClassComponent (VM9 react-dom.development.js:14388)
    at beginWork (VM9 react-dom.development.js:15206)
    at performUnitOfWork (VM9 react-dom.development.js:17944)
    at workLoop (VM9 react-dom.development.js:17984)
    at HTMLUnknownElement.callCallback (VM9 react-dom.development.js:143)
    at Object.invokeGuardedCallbackDev (VM9 react-dom.development.js:193)
    at invokeGuardedCallback (VM9 react-dom.development.js:250)
    at replayUnitOfWork (VM9 react-dom.development.js:17231)
value @ VM17 dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
finishClassComponent @ VM9 react-dom.development.js:14425
updateClassComponent @ VM9 react-dom.development.js:14388
beginWork @ VM9 react-dom.development.js:15206
performUnitOfWork @ VM9 react-dom.development.js:17944
workLoop @ VM9 react-dom.development.js:17984
callCallback @ VM9 react-dom.development.js:143
invokeGuardedCallbackDev @ VM9 react-dom.development.js:193
invokeGuardedCallback @ VM9 react-dom.development.js:250
replayUnitOfWork @ VM9 react-dom.development.js:17231
renderRoot @ VM9 react-dom.development.js:18103
performWorkOnRoot @ VM9 react-dom.development.js:18961
performWork @ VM9 react-dom.development.js:18873
performSyncWork @ VM9 react-dom.development.js:18847
batchedUpdates$1 @ VM9 react-dom.development.js:19060
batchedUpdates @ VM9 react-dom.development.js:2148
dispatchEvent @ VM9 react-dom.development.js:5002
```

## Your Environment
* Browser name and version: Chrome
* Operating System and version: Mac

**Comment by ArenHarut** [comment]
Same for me.

**Comment by Pixelartist** [comment]
Same for me - trying to additional value by this log:
`7ac9412e-fed4-4afe-b684-ecbea7da08fd--status-pages.js:3552 Uncaught TypeError: Cannot read property 'inputValue' of undefined
    at StatusPagesDashboard.render (7ac9412e-fed4-4afe-b684-ecbea7da08fd--status-pages.js:3552)
    at finishClassComponent (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:14425)
    at updateClassComponent (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:14388)
    at beginWork (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:15206)
    at performUnitOfWork (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17944)
    at workLoop (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17984)
    at HTMLUnknownElement.callCallback (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:143)
    at Object.invokeGuardedCallbackDev (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:193)
    at invokeGuardedCallback (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:250)
    at replayUnitOfWork (d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17231)
render @ 7ac9412e-fed4-4afe-b684-ecbea7da08fd--status-pages.js:3552
finishClassComponent @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:14425
updateClassComponent @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:14388
beginWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:15206
performUnitOfWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17944
workLoop @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17984
callCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:143
invokeGuardedCallbackDev @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:193
invokeGuardedCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:250
replayUnitOfWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17231
renderRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18103
performWorkOnRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18961
performWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18873
performSyncWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18847
batchedUpdates$1 @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:19060
batchedUpdates @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:2148
dispatchEvent @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:5002
d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:15873 The above error occurred in the <StatusPagesDashboard> component:
    in StatusPagesDashboard (at status-page-dashboard/index.js:15)
    in Wrapper (created by Context.Consumer)
    in a
    in e

React will try to recreate this component tree from scratch using the error boundary you provided, e.
logCapturedError @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:15873
logError @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:15907
callback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:16802
callCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11288
commitUpdateEffects @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11327
commitUpdateQueue @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11318
commitLifeCycles @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:16115
commitAllLifeCycles @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17386
callCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:143
invokeGuardedCallbackDev @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:193
invokeGuardedCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:250
commitRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17582
completeRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:19036
performWorkOnRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18965
performWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18873
performSyncWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18847
batchedUpdates$1 @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:19060
batchedUpdates @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:2148
dispatchEvent @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:5002
ListPicker._handleMouseUp
d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:500 Warning: e: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
warningWithoutStack @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:500
callback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:16811
callCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11288
commitUpdateEffects @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11327
commitUpdateQueue @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:11318
commitLifeCycles @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:16115
commitAllLifeCycles @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17386
callCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:143
invokeGuardedCallbackDev @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:193
invokeGuardedCallback @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:250
commitRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:17582
completeRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:19036
performWorkOnRoot @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18965
performWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18873
performSyncWork @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:18847
batchedUpdates$1 @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:19060
batchedUpdates @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:2148
dispatchEvent @ d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js:5002
ListPicker._handleMouseUp
2one-app-c0c024ce-prod.js:1 Uncaught (in promise) TypeError: Cannot read property 'postMessage' of null
    at t.value (one-app-c0c024ce-prod.js:1)
    at t.value (one-app-c0c024ce-prod.js:1)
    at t.<anonymous> (one-app-c0c024ce-prod.js:1)
    at f (one-vbp-c5a1971f-prod.js:1)
    at Generator._invoke (one-vbp-c5a1971f-prod.js:1)
    at Generator.forEach.t.<computed> [as next] (one-vbp-c5a1971f-prod.js:1)
    at r (one-vbp-c5a1971f-prod.js:1)
    at c (one-vbp-c5a1971f-prod.js:1)
    at one-vbp-c5a1971f-prod.js:1
    at nrWrapper (nr-loader-spa-current.min.js:1)`

**Comment by danifitz** [comment]
Same here, had the same error message as @Pixelartist 

```
Uncaught (in promise) TypeError: Cannot read property 'postMessage' of null
    at t.value (one-app-efac471f-prod.js:1)
    at t.value (one-app-efac471f-prod.js:1)
    at t.<anonymous> (one-app-efac471f-prod.js:1)
    at f (one-vbp-f0dfdda9-prod.js:1)
    at Generator._invoke (one-vbp-f0dfdda9-prod.js:1)
    at Generator.forEach.t.<computed> [as next] (one-vbp-f0dfdda9-prod.js:1)
    at r (one-vbp-f0dfdda9-prod.js:1)
    at c (one-vbp-f0dfdda9-prod.js:1)
    at one-vbp-f0dfdda9-prod.js:1
    at nrWrapper (nr-loader-spa-current.min.js:1)
```

**Comment by SultanSGillani** [comment]
Same for me. Are you guys even updating this?

**Comment by aminoz007** [comment]
I created this pull request to fix this bug: https://github.com/newrelic/nr1-status-pages/pull/117

**Comment by jpvajda** [comment]
#117 is now merged in, so if this bug is resolved feel free to close it @jsbnr
