### ISSUE TITLE
Deleting Status page services in wrong order

### ISSUE THREAD

**Issue by zelda2626** [newrelic/nr1-status-pages#122]
The deletion is done by hostname.hostName. If you have an StatusPage service that has hostname it will be deleted as it is mean to be. But if you have that plus several NRQL services and try to delete one of the NRQL ones, the deletion won't be correct, because in the handler you find the index by hostName and NRQL components don't have hostName. It must be performed by id.

**Comment by shahramk** [comment]
PR #167 fixes this issue
