### ISSUE TITLE
No longer able to add services

### ISSUE THREAD

**Issue by jakeHinton** [newrelic/nr1-status-pages#134]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Add Service slide out, the Add Service button not longer adds services

## Steps to Reproduce
Click Add new services
Select any Pre-fills or fill in form with a status page
Click Add New Service

## Expected Behaviour
Services should be added 

## Relevant Logs / Console output
one-app-9a6bdf85.js:1 No LAUNCHER found with ID: 'dd63659f-6f57-42f2-9428-c5ad151c35af.status-page-launcher'.
x @ one-app-9a6bdf85.js:1
b @ one-app-9a6bdf85.js:1
O @ one-app-9a6bdf85.js:1
N @ one-app-9a6bdf85.js:1
t.transformLegacyLocationToHurlAppState @ one-app-9a6bdf85.js:1
YMil.t.default @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
a @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
n @ one-vbp-ba25e7cd.js:1
c @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
nrWrapper @ us-1211.js:1
r @ us-1211.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
t.subscribe @ one-app-9a6bdf85.js:1
t.listen @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
A9C8.t.default @ one-app-9a6bdf85.js:1
u6CZ @ one-app-9a6bdf85.js:1
c @ one-app-9a6bdf85.js:1
n @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
one-app-9a6bdf85.js:1 No LAUNCHER schema found with ID: 'dd63659f-6f57-42f2-9428-c5ad151c35af.status-page-launcher'
x @ one-app-9a6bdf85.js:1
O @ one-app-9a6bdf85.js:1
N @ one-app-9a6bdf85.js:1
t.transformLegacyLocationToHurlAppState @ one-app-9a6bdf85.js:1
YMil.t.default @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
a @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
n @ one-vbp-ba25e7cd.js:1
c @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
nrWrapper @ us-1211.js:1
r @ us-1211.js:1
(anonymous) @ one-vbp-ba25e7cd.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
t.subscribe @ one-app-9a6bdf85.js:1
t.listen @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
A9C8.t.default @ one-app-9a6bdf85.js:1
u6CZ @ one-app-9a6bdf85.js:1
c @ one-app-9a6bdf85.js:1
n @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
(anonymous) @ one-app-9a6bdf85.js:1
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/837f18bf9fa56310.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/4871b60b13f4c2c5.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/71bf1b4a6cf50d9b.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/eff4c38a3f4b03c5.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/8d97042de18680a7.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/a59b4c8bde54e941.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/b39395de4a3c99ed.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/06a0dbb5dc87cb60.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/7ae7dca613465488.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/31285f1fb6b28592.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/5259d17b9faddaea.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/5259d17b9faddaea.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/4871b60b13f4c2c5.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/eff4c38a3f4b03c5.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/71bf1b4a6cf50d9b.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/a59b4c8bde54e941.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/8d97042de18680a7.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/b39395de4a3c99ed.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/837f18bf9fa56310.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/837f18bf9fa56310.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/837f18bf9fa56310.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/e220f3e807a4c011.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/06a0dbb5dc87cb60.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://cli-assets.service.datanerd.us/platform/7ae7dca613465488.map: Load canceled due to load timeout
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
V2 user, Admin and User
MacBook Pro BigSur 11.6
Chrome 93.0.4577.82

**Comment by jpvajda** [comment]
I'm going to evaluate what might be occurring here. Thanks for reporting this @jakeHinton

**Comment by jpvajda** [comment]
I was able to add services on our staging account @jakeHinton is there a specific account you are attempting to use this app with? Is it on productin or staging?

<img width="945" alt="Screen Shot 2022-02-15 at 3 27 11 PM" src="https://user-images.githubusercontent.com/1395158/154160344-459b2a17-a6ea-474d-a06a-ce635d86b884.png">

**Comment by jpvajda** [comment]
So after trying this test again, now it's failing as reported.

**Comment by jpvajda** [comment]
@rudouglas thanks for looking at this in the Irish morning. 🇮🇪  Let us know what you find in your exploration. 🙏

**Comment by rudouglas** [comment]
I think i've found the issue here, there was a change introduced as part of [this commit](https://github.com/newrelic/nr1-status-pages/commit/ea7ddc6521794f049aecdc8db5e4ee28d5b15628) to check whether a Quick Selection contained `nrql` or `workload`, but was checking the positive instead of the negative.

I made these changes and published to my personal account and I am able to add services now

This is likely still blocked by the catalog publishing issue though right @jpvajda https://github.com/newrelic/nr1-catalog/issues/435
