### ISSUE TITLE
Workload and NRQL based status pages don't work

### ISSUE THREAD

**Issue by nr-pmoses** [newrelic/nr1-status-pages#141]
## I have used the straightforward steps of adding a new service configuration and selected workload entered the workload GUID, and saved the view, similarly with NRQL as per the 2 config screenshots [attached]([[(https://www.dropbox.com/s/hepov5bxhqbqzxj/Screen%20Shot%202022-03-09%20at%209.24.56%20am.png?dl=0)](https://www.dropbox.com/s/yseftvqrql4u7m0/Screen%20Shot%202022-03-09%20at%2010.28.25%20am.png?dl=0)]])

Status pages nerdpack for workloads/NRQL: I get this error "[Error] Failed to load resource: The request timed out. (7667e68d3a423067.map, line 0)" when trying to use status pages for NRQL or for workloads. I have tested on multiple NR accounts 

## Steps to Reproduce

See above config screenshots for config used to replicate the issue

## Expected Behaviour

Expecting not to get an error "There was an error while fetching data. Check your data provider or host URL."

## Relevant Logs / Console output

"[Error] Failed to load resource: The request timed out. (7667e68d3a423067.map, line 0)" 

## Your Environment

New Relic Enterprise account with admin access.

* NR1 CLI version used: Latest
* Browser name and version: Safari and Chrome latest
* Operating System and version: Mac OS latest

**Comment by nr-pmoses** [comment]
<img width="2555" alt="Screen Shot 2022-03-09 at 10 28 25 am" src="https://user-images.githubusercontent.com/78463884/157345559-42558754-f658-448e-86b9-6881752fec11.png">
<img width="2549" alt="Screen Shot 2022-03-09 at 9 24 56 am" src="https://user-images.githubusercontent.com/78463884/157345565-19012c00-99bd-47a9-9111-3a3344bd0b5d.png">

Sharing config screenshots

**Comment by shahramk** [comment]
@nr-pmoses, I tried both workloads and nrqls in my account, and they both worked. I'd appreciate if you could try it again, and if the issue still persists, give me more context.

thank you

**Comment by shahramk** [comment]
@nr-pmoses, since I find no issues with workload nor nrql based status pages, I am closing this issue. If you find any persisting problems, please update this issue.
