### ISSUE TITLE
Search on status page not working

### ISSUE THREAD

**Issue by carlos-r-mendoza** [newrelic/nr1-status-pages#181]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Search on status page does nothing. When a value is inputted into the search box, nothing happens on the page. 

<img width="1108" alt="Screenshot 2024-01-08 at 3 59 22 PM" src="https://github.com/newrelic/nr1-status-pages/assets/7957679/51f95e91-46b2-4c54-b2f7-26bc0a00c2e9">

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
After having added the Status Pages app and at least one service, attempt to use the search box to filter.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
Tiles are filtered based on service name.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
N/A

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: N/A
* Browser name and version: Google Chrome Version 120.0.6099.199
* Operating System and version: macOS 13.6

## Additional context
N/A

[TIP]:  # ( Add any other context about the problem here. )

**Comment by shahramk** [comment]
@carlos-r-mendoza, the search function is a filtering mechanism, which in cases where your services exceed one page on the screen, it allows you to filter to specific services by name, so that you don't have to scroll up/down to see a particular service.
