### ISSUE TITLE
Account selector dropdown is NOT evident upon installation

### ISSUE THREAD

**Issue by DanPerovich** [newrelic/nr1-status-pages#21]
After installing this NerdPack and configuring one or more status pages to use, I was left scratching my head why nothing was showing in the Nerdlet.  It was not apparent that I needed to first select an account from the account dropdown (between the 'Refresh rate' dropdown and 'Edit StatusPages' button) before the status page summaries that I configured would be displayed.

I suggest auto-selecting the first account in the list, displaying a message to tell the user to select an account, and/or putting something like 'Select Account' as the default text in the account selector dropdown.

**Comment by ericSpence** [comment]
Are you seeing any accounts in the dropdown? I am currently seeing an issue where AccountsQuery.query is returning an empty set which maybe part of the problem.

**Comment by DanPerovich** [comment]
> Are you seeing any accounts in the dropdown? I am currently seeing an issue where AccountsQuery.query is returning an empty set which maybe part of the problem.

Yes, I am seeing accounts in the dropdown.

**Comment by ericSpence** [comment]
This issue looks like it will be addressed by #23
