### ISSUE TITLE
Redesign in the open

### ISSUE THREAD

**Issue by danielgolden** [newrelic/nr1-status-pages#23]
Working on a redesign of this nerdpack, going to log the progress in an issue here.

**Comment by danielgolden** [comment]
### Early peek into what will become draft 1 
<img width="1434" alt="Captura de Pantalla 2019-10-11 a la(s) 2 10 07 p  m" src="https://user-images.githubusercontent.com/812989/66674433-dd7c3180-ec30-11e9-94ec-5a3a77492484.png">

---

#### Feedback received from Freddy (response in bold)
- Date may not be sufficient on the timeline, may also need time? 
(**True, will be in detail view. Should include it anyway?**)
- Should definitely give them the option of editing title/logo, were you thinking they choose Title OR Logo?
(**Title and/or logo. If they include both we can stuff the service name into `title` attribute of `<img />`**)
- The best experience will be if we setup logos for a bunch of common ones, but still allow them to point to arbitrary url's. Auto-pulling them in will be hard due to variation in location
Other feedback/ideas:
(**Sounds good**)
- Search/filtering to easily find the one you're looking for, maybe they wouldn't have enough of these to matter, but it seems plausible. Maybe we toggle it available after X items.
(**Good idea**)
- Ability to re-order cards
(**Another good idea**)

**Comment by danielgolden** [comment]
## Draft 1
Primary screen
<img width="1440" alt="Draft 1 - Primary Screen" src="https://user-images.githubusercontent.com/812989/66762028-2a4f4a80-ee73-11e9-89eb-82bd47efefe6.png">
Details screen
<img width="1440" alt="Draft 1 - Details Screen" src="https://user-images.githubusercontent.com/812989/66762026-2a4f4a80-ee73-11e9-8886-58c993b2fc6d.png">

**Comment by danielgolden** [comment]
Got the green light on this. Going to start building now

**Comment by ericSpence** [comment]
Looks great!

**Comment by danielgolden** [comment]
@ericSpence Thanks, man! Just submitted the PR for the changes: https://github.com/newrelic/nr1-status-pages/pull/25

**Comment by danielgolden** [comment]
PR merged and [new release drafted](https://github.com/newrelic/nr1-status-pages/releases).
