### ISSUE TITLE
CORS errors for some status pages

### ISSUE THREAD

**Issue by aminoz007** [newrelic/nr1-status-pages#24]
https://status.slack.com/ will fail with a CORS error, many others status pages have the same problem. This is a known issue since browser will block any server call that is not initiated from the same domain when the server does not allow CORS. I've encountered this issue many times, there is no easy way around it!

I can think only about 2 options:
1- See if RSS Feed helps
2- Create and use a proxy server

**Comment by borregovenegas** [comment]
Hi, having the same problem while trying to implement AWS service into the Status Page.

![image](https://user-images.githubusercontent.com/23413021/75814975-40917080-5d58-11ea-9bb7-703838a11566.png)

**Comment by ericSpence** [comment]
I think having a generic RSS Feed parser would help with a lot of these sites.

**Comment by devfreddy** [comment]
# Targets

## Slack

[Website](https://status.slack.com/)
[Atom Feed](https://status.slack.com/feed/atom)
[RSS Feed](https://status.slack.com/feed/rss)

## Zendesk (Issue #38 )

[Website](https://status.zendesk.com)
[Incidents JSON Feed](https://status.zendesk.com/api/internal/incidents.json?as_of_date=2020-03-23&days_back=90) - utilizes parameters `as_of_date=2020-03-23` and `days_back=90`

## Gitlab (Issue #34)

[Website](https://status.gitlab.com/)
[RSS Feed](https://status.gitlab.com/pages/5b36dc6502d06804c08349f7/rss) - Has a hash in the url - will need to keep in mind this could change... could also just be where/how they're hosting it.

**Comment by devfreddy** [comment]
Closing. Tracking the broader issue in #45.
