### ISSUE TITLE
Nerdpack failing & crashing. 

### ISSUE THREAD

**Issue by ryanv94** [newrelic/nr1-status-pages#26]
Since the redesign by @danielgolden - (redesign looks fantastic btw) - I can't get this nerdpack to work. I have attached a video, where upon selecting a service, I get a non-stop spinner. 

When I try to manually add a service, I can click the text inputs, but typing anything immediately results in the nerdpack crashing. **This happens in Safari.** 

**This Nerdpack works as expected in Chrome.** 

Video: https://drive.google.com/file/d/1bZZ96REvdD1qY-xFuWok6TU4AdNiIOyL/view?usp=sharing

**Comment by danielgolden** [comment]
@ryanv94 Thanks for the heads up on this issue. I'm going to take a look into it today.

**Comment by danielgolden** [comment]
Resolved in #27 which was just merged into master. Thanks again, for the heads up, Ryan!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
