### ISSUE TITLE
Support for https://status.gitlab.com/

### ISSUE THREAD

**Issue by marcincuber** [newrelic/nr1-status-pages#34]
## Summary

I would like to be able to display status pages for hashicorp and gitlab. Currently, they don't seem to be working. I believe they are very popular services so ideally I am not the only one who would like to see them available.  

## Desired Behaviour

Simply be able to add https://status.hashicorp.com/ + https://status.gitlab.com/ and seeing the results in the NewRelic UI.

## Additional context

I relay on gitlab cloud and terraform cloud so it would be a fantastic feature to add so I can have all status pages in a centralised UI.

**Comment by eric-spence-code** [comment]
@marcincuber just doubled checked hashicorp seems to be using status page io so it should already be able to be integrated. Just make sure to select status page. It does look like gitlab will take additional work to add support for. I do think adding a generic RSS feed handler could be a useful functionality.

**Comment by ericSpence** [comment]
@marcincuber just doubled checked hashicorp seems to be using status page io so it should already be able to be integrated. Just make sure to select status page. It does look like gitlab will take additional work to add support for. I do think adding a generic RSS feed handler could be a useful functionality.

**Comment by marcincuber** [comment]
@ericSpence I confirm that hashicorp works as expected which is great.

Gitlab still not working. Perhaps a nice new feature/enhancement to add.

**Comment by devfreddy** [comment]
Closing. Tracking the broader issue in #45.
