### ISSUE TITLE
Issues with the NR1 Status Pages app on Safari

### ISSUE THREAD

**Issue by Cammy-Wammy** [newrelic/nr1-status-pages#49]
The issue is with Safari (Chrome works):

1. Add new service, type anything into the “Service name” field.
![image (4)](https://user-images.githubusercontent.com/18454262/81991037-5b147f80-960e-11ea-9a83-a2affe0d3847.png)

2. Oops! page comes up on the first character typed.
![image (5)](https://user-images.githubusercontent.com/18454262/81991035-5b147f80-960e-11ea-970c-26da32d58a28.png)

**Comment by norbertsuski** [comment]
I'm on it
