### ISSUE TITLE
Weirdly status.io doesn't load

### ISSUE THREAD

**Issue by ricegi** [newrelic/nr1-status-pages#6]
https://status.status.io just hangs

**Comment by tschmidtnimble** [comment]
Would love to see status.io supported.

**Comment by tschmidtnimble** [comment]
Attempting to add the provider
https://github.com/tschmidtnimble/nr1-status-pages/commit/b9460ec2eb7ed87357516c78b05cb6f59290d162

**Comment by tschmidtnimble** [comment]
@devfreddy , would you mind reviewing the build associated with this PR? Looks like the build pipeline is a work in progress?

**Comment by marcincuber** [comment]
It looks like status.io still doesn't work. For example; https://status.docker.com/

**Comment by tschmidtnimble** [comment]
@marcincuber , try https://status.docker.com/pages/history/533c6539221ae15e3f000031

**Comment by marcincuber** [comment]
@tschmidtnimble the end of the url seems like the missing piece of puzzle. With the endpoint you provided, everything works as expected.

**Comment by devfreddy** [comment]
@tschmidtnimble Looking through status.io documentation, is it safe to assume that identifier is the [`statuspage_id`](https://statusio.docs.apiary.io/#reference/incidents/list-incidents-by-id/incident/list)?

I'm going to work on some updates to the README to reflect the needed format(s) by provider.

**Comment by tschmidtnimble** [comment]
@devfreddy, that is my understanding, yes. 

A thought: we could make it simpler for users by parsing the identifier from the web response for the url (eg. https://status.docker.com/). Looking at the page source and searching for `533c6539221ae15e3f000031` confirms its possible.

**Comment by madecki** [comment]
StatusIo works fine while following guidelines in https://github.com/newrelic/nr1-status-pages/blob/develop/README.md

> Status.io
> Url Format: {baseUrl}/pages/history/{numeric statuspage_id}
> 
> Example hostnames:
> 
> https://ezidebit.status.io/pages/history/598a973f96a8201305000142
> https://status.docker.com/pages/history/533c6539221ae15e3f000031
