### ISSUE TITLE
The animation between the settings and primary vue is not working well

### ISSUE THREAD

**Issue by aminoz007** [newrelic/nr1-status-pages#62]
**handleTileSettingsAnimation** function is handling animation between the settings content and primary content. When the primary content is active, we are still able to interact with the settings vue which should be hidden in this case.

See screenshot.

<img width="421" alt="Screen Shot 2020-06-29 at 3 28 49 PM" src="https://user-images.githubusercontent.com/40477042/86064437-efea0580-ba21-11ea-9c32-9336b380aac0.png">

**Comment by norbertsuski** [comment]
Working on this

**Comment by aminoz007** [comment]
> Working on this. It's worth to add here, that it's happening on Safari.
It is happening in Chrome for me... that's the browser I use... I will have to test the fix!
