### ISSUE TITLE
Add "RSS Feed" as a provider

### ISSUE THREAD

**Issue by aminoz007** [newrelic/nr1-status-pages#80]
We need to add RSS feed as a provider

## Summary

Many status pages don't adhere to the status IO or statusPage IO spec/standard. However, most of them support RSS feed which has the same xml structure regardless of the status page using it. It will be interesting to include an RSS feed parser as an option to support status pages that don't provide APIs. This react lib can help achieving this goal: https://www.npmjs.com/package/rss-parser

## Desired Behaviour
The customer can choose in the list of provider: "RSS Feed". Using the RSS feed parser we can get the list of incidents, we have to display the incidents in the same format as the current format (top incidents and then when we click we open the list of all incidents). RSS feed does not provide the summary status (e.g. "All operational"), so we can replace the traffic light and summary with a link, by clicking on the link we should open a stacked nerdlet that has an Iframe of the status page: "<iframe src={hostname} />; 

## Additional context

This has been requested by many people.

**Comment by aminoz007** [comment]
There is an example here: https://github.com/newrelic-experimental/nr1-rssreader

**Comment by aminoz007** [comment]
@norbertsuski I tested the rss parser with New Relic status page and it returned the list of incident as expected. My only problem is with the iframe.

**Comment by aminoz007** [comment]
Another remark: the CORS proxy should be configurable since some people may use their own internal proxy.  **https://cors-anywhere.herokuapp.com/** can be selected by default but we should be able to change it. Currently, https://cors-anywhere.herokuapp.com/ has a limit of 100 request per referrer per hour, so a customer will need to use his own proxy server to avoid this limitation. Ideally, by default *https://cors-anywhere.herokuapp.com/* is used, however this URL should be configurable.

**Comment by aminoz007** [comment]
I spent a lot of time trying to get the Iframe to work for the RSS feed but it seems very hard to implement.<br /> <br /> The "connexion refused" and "refused to display" errors are all because some sites like "Slack" don't allow CORS. <br /> <br />I tried to use the Proxy to get the html and then pass it as **srcDoc** for the iframe, that actually worked, it returned the HTML in the stacked nerdlet, however the CSS and images were not loaded because the HTML I got back from the proxy has relative paths (example: `<link rel="stylesheet" href="/css/v2/averta-font.css">`).<br /><br /> To get the CSS and Images/Fonts, I manipulated the HTML returned by the proxy and added the absolute URL with the proxy url (`<link rel="stylesheet" href="https://api.allorigins.win/raw?url=https://status.slack.com//css/v2/averta-font.css">`), I have used this snippet: <br /><br />  

> const url = "https://api.allorigins.win/raw?url="+this.props.src;
>     const networkResponse = await axios.get(url);
>     let updatedHtml = networkResponse.data.replace(/src="(.*?)"/g, `src="${url}$1"`);
>     updatedHtml = networkResponse.data.replace(/href="(.*?)"/g, `href="${url}$1"`); 

<br /> That actually worked and added the styles properly, however when I clicked on anything in the Iframe the style was gone. <br /> I think I might be able to fix that as well but it seems like a lot of work for a small thing.<br /> Besides, we can't guarantee that it will work properly for all external status pages. <br /> I will let you take a look, but if you share my opinion it would be probably easier to change the "See status page button" into a link and open the page in a different window (see screenshot below). <br /><br />
<img width="1256" alt="Screen Shot 2020-07-18 at 1 09 02 AM" src="https://user-images.githubusercontent.com/40477042/87848292-998b1c80-c893-11ea-8f54-15ab5b1b58a3.png">

**Comment by tangollama** [comment]
@aminoz007 I'm inclined to close this again based on #82. Please confirm.
